<template>
  <div class="home">
    <!-- 我的  页面留白 -->
    <div class="top">
      <div class="bar"></div>
      <div class="title">
        <span class="span">hi~ {{personal.nickname}}</span>
        <img v-lazy="personal.avatarUrl" alt="" />
      </div>
      <!-- 轮播图 -->
      <swiper id="swiper" v-if="banner.length != ''" :banner = 'banner'></swiper>
    </div>
    <!-- <swiper></swiper> -->
    <el-row class="el-row" id="top">
      <el-button class="button slide-in-blurred-right" size="small" round
        >最新歌曲</el-button
      >
      <el-button class="button slide-in-blurred-right" size="small" round
        >推荐歌单</el-button
      >
      <el-button class="button slide-in-blurred-right" size="small" round
        >流行电台</el-button
      >
      <el-button class="button slide-in-blurred-right" size="small" round
        >推荐MV</el-button
      >
    </el-row>
    <nav-little></nav-little>
    <history-record v-if="listenMusicHistury.length != 0" :listenMusicHistury = 'listenMusicHistury'></history-record>
    <recommend-info v-if="video.length != 0" :video='video'></recommend-info>
    <dig-album :paidAlbums='paidAlbums'></dig-album>
  </div>
</template>

<script>
import swiper from '../../components/swiper/swiper';
import navLittle from './navLittle';
import historyRecord from './historyRecord';
import recommendInfo from './recommendInfo';
import digAlbum from './paidAlbums';

import { getLogin, getRecommendedsongs, getBanner, getVideo, getHistoryRrecord, getDigAlbum } from "../../network/home.js";
export default {
  name: "Home",
  components: {
    historyRecord,
    swiper,
    navLittle,
    recommendInfo,
    digAlbum
  },
  data() {
    return {
      phone: "17572696252",
      password: "xybwdhxd0422",
      personal: {},
      recmmengSong: [],
      type: 2, //获取 banner数据
      banner: [],
      video: [],
      offset: 6,
      uid: '3970607697',
      listenMusicHistury: [],//最近听歌数据
      paidAlbums: [], //获取数字专辑
    };
  },
  created() {
    this.getLogin(this.phone, this.password); //用户数据
    this.getRecommendedsongs()  //最新歌曲
    this.getBanner(this.type)
    this.getVideo(this.offset)
    this.getHistoryRrecord(this.uid)
    this.getDigAlbum(this.uid)  //获取数字专辑
  },

  methods: {

    getLogin(phone, password) {
      getLogin(phone, password).then((res) => {
        // console.log(res);
        this.personal = res.data.profile;
        this.uid = this.personal.userId
        // console.log(this.personal);
      });
    },
    getRecommendedsongs() {
      getRecommendedsongs().then((res) => {
        // console.log(res);
        this.recmmengSong = res.data.result[0]
          // console.log(this.recmmengSong == '');
      });
    },
    getBanner(type){
      getBanner(type).then(res => {
        // console.log(res);
        this.banner = res.data.banners.slice(0, 5)
        // console.log(this.banner);
      })
    },
    getVideo(offset){
      getVideo(offset).then(res =>{
        this.video = res.data.datas
      })
    },
    getHistoryRrecord(uid){
      getHistoryRrecord(uid).then(res => {
        // console.log(res);
        this.listenMusicHistury = res.data.allData.slice(0, 5)
        // console.log(this.listenMusicHistury);
      })
    },
    getDigAlbum(uid){
      getDigAlbum(uid).then(res =>{
        console.log(res);
        this.paidAlbums = res.data.paidAlbums
        console.log(this.paidAlbums);
      })
    }
  },
};
</script>

<style scomed>
#home{
  width: calc(100% - 5%);
  overflow: hidden;
}
.top{
  background-color: #fff;
  padding: 0 2%;
  background-image: linear-gradient(#fff, #f1f1f1);
}
#top{
  margin-top: 1rem;
  margin-left: 2%;
  width: calc(100% -  5%)
}
.bar {
  height: 6vh;
  width: calc(100% - 5%);
}
.span {
  margin: 0px;
  font-weight: 400;
  text-align: center;
  line-height: 60px;
}
.title {
  display: flex;
  width: calc(100% - 5%);
  justify-content: space-between;
}
#swiper{
  width: calc(100% - 5%);
  border-radius: 8px;
}
.title img {
  width: 10%  !important;
  border-radius: 50px;
  margin-bottom: 20px;
  vertical-align: middle;
}

.button {
  color: ccc;
}

.slide-in-blurred-right {
  -webkit-animation: slide-in-blurred-right 0.6s cubic-bezier(0.23, 1, 0.32, 1)
    both;
  animation: slide-in-blurred-right 0.6s cubic-bezier(0.23, 1, 0.32, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-4-20 23:37:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-blurred-right {
  0% {
    -webkit-transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 0% 50%;
    transform-origin: 0% 50%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-right {
  0% {
    -webkit-transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 0% 50%;
    transform-origin: 0% 50%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
