<template>
  <div id="nav-little">
    <div class="nav-info">
      <div class="nav-item slide-in-blurred-right"  v-for="item in title" :key="item.key">
        <i :class="item.id" class="font"></i>
        <p>{{item.name}}</p>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  name: "navLittle",
  data(){
    return{
      title: [
        {id: 'iconfont icon-icon_xinyong_xianxing_jijin-133', name: '推荐'},
        {id: 'iconfont icon-paihangbang', name: '榜单'},
        {id: 'iconfont icon-diantai', name: '电台'},
        {id: 'iconfont icon-MV', name: 'MV'},
        {id: 'iconfont icon-new', name: '新歌榜'},
      ]
    }
  }
}
</script>
<style scoped>
#nav-little{
  width: 100%;
  width: calc(100% - 4%);
  /* height: 7vh; */
  border-radius: 8px;
  margin: 2% 2%;
  background-color: #fff;
}
.nav-info{
width: calc(100% - 4%);
  display: flex;
  justify-content: space-between;
}
.nav-item{
  /* width: 21%; */
  height: 100%;
  line-height: 2vh;
  padding: 2%;
  border-radius: 8px;
  text-align: center;
  padding-top: 1.7rem;
}
.font{
  font-size: 1.6rem;
  background-color: red;
  padding: 4px;
  border-radius: 10px;
}
p{
  margin: 0px;
  margin-top: 1rem;
}

.slide-in-blurred-right {
  -webkit-animation: slide-in-blurred-right 0.6s cubic-bezier(0.23, 1, 0.32, 1)
    both;
  animation: slide-in-blurred-right 0.6s cubic-bezier(0.23, 1, 0.32, 1) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-4-20 23:37:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-blurred-right
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-blurred-right {
  0% {
    -webkit-transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 0% 50%;
    transform-origin: 0% 50%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes slide-in-blurred-right {
  0% {
    -webkit-transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    transform: translateX(1000px) scaleX(2.5) scaleY(0.2);
    -webkit-transform-origin: 0% 50%;
    transform-origin: 0% 50%;
    -webkit-filter: blur(40px);
    filter: blur(40px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0) scaleY(1) scaleX(1);
    transform: translateX(0) scaleY(1) scaleX(1);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
